# Generated by Django 4.0.2 on 2024-01-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nb_conn_max', models.IntegerField(blank=True, default=1, null=True)),
                ('version', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.TextField(blank=True, max_length=700, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=100, null=True)),
                ('sessionid', models.TextField(blank=True, max_length=350, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_applications', to='btapps.application')),
            ],
            options={
                'unique_together': {('application', 'utilisateur', 'token', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='Droit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droit_applications', to='btapps.application')),
            ],
            options={
                'unique_together': {('application', 'utilisateur')},
            },
        ),
    ]
