# Generated by Django 4.0.2 on 2024-08-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('reset_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('used', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
